// frontend/src/components/PostCreate.vue
<template>
  <div class="glass post-create-card animate-slide-down">
    <h3>Create a Post</h3>
    <form @submit.prevent="submitPost">
      <textarea 
        v-model="content" 
        class="input-field content-input" 
        placeholder="Write your post... You can use HTML like <b>bold</b> or <span style='color: red'>red text</span>."
        rows="4"
        required
      ></textarea>
      
      <div class="submit-row">
        <span class="hint">Tags allowed: div, span, b, i, style attributes.</span>
        <button type="submit" class="btn-primary" :disabled="loading || !content.trim()">
          {{ loading ? 'Posting...' : 'Post' }}
        </button>
      </div>
    </form>
    <div v-if="error" class="error-text">{{ error }}</div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import api from '../api';

const emit = defineEmits(['post-created']);
const content = ref('');
const loading = ref(false);
const error = ref('');

const submitPost = async () => {
  if (!content.value.trim()) return;
  
  loading.value = true;
  error.value = '';
  
  try {
    const response = await api.post('/posts', { content: content.value });
    emit('post-created', response.data);
    content.value = '';
  } catch (err) {
    if (err.response?.status === 401) {
      error.value = 'Your session has expired. Please log in again.';
    } else {
      error.value = err.response?.data?.message || 'Failed to create post.';
    }
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.post-create-card {
  padding: 24px;
  margin-bottom: 30px;
}

h3 {
  margin-top: 0;
  margin-bottom: 16px;
  font-size: 1.2rem;
  color: var(--text-primary);
}

.content-input {
  resize: vertical;
  min-height: 100px;
  font-family: inherit;
  margin-bottom: 12px;
}

.submit-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.hint {
  font-size: 0.8rem;
  color: var(--text-secondary);
  font-style: italic;
}

.error-text {
  color: #f85149;
  font-size: 0.85rem;
  margin-top: 10px;
}
</style>

// frontend/src/pages/PostCreate.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../api';

function PostCreate({ isEdit = false }) {
    const [content, setContent] = useState('');
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(isEdit);
    const [saving, setSaving] = useState(false);
    const navigate = useNavigate();
    const { id } = useParams();

    useEffect(() => {
        if (isEdit && id) {
            fetchPost();
        }
    }, [id, isEdit]);

    const fetchPost = async () => {
        try {
            const res = await api.get('/posts');
            const post = res.data.find(p => p.id.toString() === id);
            if (post) {
                setContent(post.content);
            } else {
                setError('Post not found');
            }
        } catch (err) {
            setError('Failed to load post');
        } finally {
            setLoading(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!content.trim()) {
            setError('Post cannot be empty.');
            return;
        }
        if (content.length > 5000) {
            setError('Post exceeds maximum character limit of 5000.');
            return;
        }

        setError('');
        setSaving(true);

        try {
            if (isEdit) {
                await api.put(`/posts/${id}`, { content });
                navigate(`/post/${id}`);
            } else {
                await api.post('/posts', { content });
                navigate('/feed');
            }
        } catch (err) {
            setError('Failed to save post.');
            setSaving(false);
        }
    };

    if (loading) return <div className="container" style={{ textAlign: 'center' }}><span className="loader"></span></div>;

    return (
        <div className="container animate-fade-in">
            <h2>{isEdit ? 'Edit Post' : 'Create a New Post'}</h2>
            <div className="glass" style={{ padding: '24px', marginTop: '20px' }}>
                {error && <div className="error-banner">{error}</div>}
                <form onSubmit={handleSubmit}>
                    <label style={{ display: 'block', marginBottom: '12px', color: 'var(--text-secondary)' }}>
                        Inject your custom HTML and inline CSS below:
                    </label>
                    <textarea
                        className="input-field"
                        rows="10"
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        disabled={saving}
                        placeholder='<div style="color: red;">Hello World</div>'
                        style={{ fontFamily: 'monospace' }}
                    ></textarea>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ color: content.length > 5000 ? '#f85149' : 'var(--text-secondary)', fontSize: '0.85rem' }}>
                            {content.length} / 5000 characters
                        </span>
                        <div style={{ display: 'flex', gap: '12px' }}>
                            <button type="button" onClick={() => navigate(-1)} className="btn-secondary" disabled={saving}>Cancel</button>
                            <button type="submit" className="btn-primary" disabled={saving}>
                                {saving ? 'Saving...' : (isEdit ? 'Update Post' : 'Publish')}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default PostCreate;
